# Generated by Django 3.1.7 on 2021-05-31 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_published_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 21, 29, 18, 829111, tzinfo=utc)),
        ),
    ]
