# Generated by Django 3.2.3 on 2021-05-28 21:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210528_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 5, 28, 21, 51, 11, 996828, tzinfo=utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=250), max_length=250
            ),
        ),
    ]
