# Generated by Django 3.2.3 on 2021-05-28 22:10

import datetime

import django_extensions.db.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_post_published_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 5, 28, 22, 10, 56, 904422, tzinfo=utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
