# Generated by Django 3.2.3 on 2021-05-28 22:11

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210528_2210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 5, 28, 22, 11, 37, 505244, tzinfo=utc
                )
            ),
        ),
    ]
